module.exports = {    
  // ignoredRouteFiles: ["**/.*"],
  appDirectory: "app",
  browserBuildDirectory: "/public/build/client",
  publicPath: "/public/build/",
  getServerBuildDirectory: "/public/build/server",
  assetsBuildDirectory: "/public/build",
  serverBuildPath: "/public/build/server/index.js",
  devServerPort: 8888,
  serverEnvironmentVariables: ["API_URL", "ENCRYPTION_KEY", "SESSION_SECRET"],
  serverModuleFormat: "cjs",
  plugins: [/* other plugins */],
  serverDependenciesToBundle: ["axios", /^marked.*/],
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
};